server:
  port: 8080
  servlet:
    context-path: /grocery-service

spring:
  application:
    name: grocery-booking-api
  datasource:
    url: jdbc:postgresql://localhost:5432/grocery_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
